name: Windows

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Install Conan
        shell: bash
        run: |
          pip install conan
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

      - name: Configure
        run: cmake -DENABLE_CONAN=ON -Bbuild

      - name: Build
        run: cmake --build build
