name: Windows

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Install Boost
        run: |
          $Url = "https://sourceforge.net/projects/boost/files/boost-binaries/1.72.0/boost_1_72_0-msvc-14.2-64.exe"
          (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
          Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\hostedtoolcache\windows\Boost\1.72.0\x86_64"

      - name: Install Conan
        shell: bash
        run: |
          if grep ENABLE_CONAN CMakeLists.txt | grep -w ON &>/dev/null ; then
            pip install conan
            conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          fi

      - name: Configure
        run: cmake -Bbuild

      - name: Build
        run: cmake --build build
